services:
  mysql:
    image: mysql:8.0
    container_name: ledger_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: ledger_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql


  api:
    build: .
    container_name: ledger_api
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env

volumes:
  mysql_data:
